--- #YAML:1.0
name:                Language-Befunge-Vector-XS
version:             1.1.0
abstract:            Language::Befunge::Vector rewritten for speed
license:             perl
author:              
    - Jerome Quelin, <jquelin@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
